name: drawli_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3 #version name + versioncode

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0 # 웹뷰

  permission_handler: ^11.3.0 # 권한 관리

  cupertino_icons: ^1.0.2

  url_launcher: ^6.2.5

  lottie: ^1.0.1

  # tosspayment
  tosspayments_sdk_flutter: ^0.2.0

  # firebase push
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10 # 파이어베이스 푸시
  flutter_local_notifications: ^16.3.2 # 로컬 푸시

  # file downloader
  flutter_downloader: ^1.8.4 # 파일 다운로더
  path_provider: ^2.1.2 # 파일 경로
  open_file: ^3.3.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

assets:
  - assets/lottie/splash_fast.json
