// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSTaRTxtimd4YdDu-DFMx_CVSUwtKp8vA',
    appId: '1:83757875514:web:7d4f3de7c560dec2359003',
    messagingSenderId: '83757875514',
    projectId: 'drawli-android',
    authDomain: 'drawli-android.firebaseapp.com',
    storageBucket: 'drawli-android.appspot.com',
    measurementId: 'G-HNH70PWYZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeGm_Qy2jUaIp0jKvCEANdHiPVdExqKY',
    appId: '1:83757875514:android:be4d713f228c8b1f359003',
    messagingSenderId: '83757875514',
    projectId: 'drawli-android',
    storageBucket: 'drawli-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11sjgv7-yyaF4oKnaFuVB3STGDB_6vcw',
    appId: '1:83757875514:ios:c100f2d2b66ee72b359003',
    messagingSenderId: '83757875514',
    projectId: 'drawli-android',
    storageBucket: 'drawli-android.appspot.com',
    iosBundleId: 'com.drawli.drawliFlutter',
  );
}
